# Generated by Django 4.1.2 on 2023-01-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdb',
            name='phonenum',
        ),
    ]
